version: '3.8'
services: 
  app: 
    build: 
        context: .
        dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment: 
      - DATABASE_URL=postgres://postgres:${secret.POSTGRES_PASSWORD}@localhost:5432/dahlia
    depends_on:
      - db
    restart: unless-stopped

  db: 
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${secret.POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: dahlia
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s 
      timeout: 5s 
      retries: 5

  volumes:
    postgres_data:
