version: '3.8'
services: 
  app: 
    build: 
        context: .
        dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment: 
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@dahlia:5432
    depends_on:
      - db
    restart: unless-stopped

  api:
    image: IntrepidT/dahlia
    environment: 
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@dahlia:5432"
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db: 
    image: postgres:15-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: dahlia
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s 
      timeout: 5s 
      retries: 5

  volumes:
    db:
      driver: local
