version: '3.8'
services: 
  leptos-app: 
    image: intrepidt/dahlia:latest
    ports: 
      - "3000:3000"
    environment: 
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/dahlia
      - LEPTOS_SITE_ADDR=0.0.0.0:3000
      - LEPTOS_SITE_ROOT=/app/LEPTOS_SITE_ADDR
      - LEPTOS_SITE_PKG_DIR=/app/site/pkg
    depends_on:
      - db
    restart: unless-stopped

  db: 
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s 
      timeout: 5s 
      retries: 5

volumes:
  postgres-data:
