use leptos::prelude::*;
pub mod add_employee_form;
pub mod delete_confirmation;
pub mod employee_details;
pub mod employee_table;
pub mod role_selector;
pub mod search_filter;
pub mod teacher_table;
pub mod update_employee_form;
pub mod user_table;

pub use add_employee_form::*;
pub use delete_confirmation::*;
pub use employee_details::*;
pub use employee_table::*;
pub use role_selector::*;
pub use search_filter::*;
pub use teacher_table::*;
pub use update_employee_form::*;
pub use user_table::*;
